### ISSUE TITLE
Bug: Serialization of expando adds valuekind

### ISSUE THREAD

**Issue by YogirajA** [HeadspringLabs/Totem#108]
Tests on example app started to fail with error:
```
A total of 1 test files matched the specified pattern.
  X SalesOrderApp.PlaceOrderTests.ShouldReturnSuccessForValidContract [4s 110ms]
  Error Message:
   Response status code does not indicate success: 400 (Bad Request).
  Stack Trace:
  System.Net.Http.HttpRequestException
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at SalesOrderApp.PlaceOrderTests.ShouldReturnSuccessForValidContract() in C:\code\Totem\examples\SalesOrderApp\PlaceOrderTests.cs:line 48
  Standard Output Messages:
 Message does not match contract: Message is missing expected property "Id". Message is missing expected property "ItemName". Message is missing expected property "OrderDate". Message is missing expected property "OrderId". Message is missing expected property "Timestamp".
```

This was noticed after .NET core upgrade. After debugging, it turns out JSON serializer in .NET doesn't support Expando objects completely as tracked in https://github.com/dotnet/runtime/issues/29690 . For our purposes, we were seeing `valuekind` being added in the message body. That was breaking serialization in Totem.Features.API.TestMessage.cs.

**Comment by YogirajA** [comment]
Instead of `JsonConvert.SerializeObject(request.Message);` , just having `request.Message.ToString()` is sufficient.
